apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nodejs-demo.fullname" . }}-config
  labels:
    {{- include "nodejs-demo.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.env.nodeEnv | quote }}
  PORT: {{ .Values.env.port | quote }}
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}
  DB_HOST: {{ .Values.database.host | quote }}
  DB_PORT: {{ .Values.database.port | quote }}
  DB_NAME: {{ .Values.database.name | quote }}
  REDIS_HOST: {{ .Values.redis.host | quote }}
  REDIS_PORT: {{ .Values.redis.port | quote }}
