{{- if .Values.redisCache.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    app: redis
    {{- include "nodejs-demo.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
  selector:
    app: redis
{{- end }}
