{{- if .Values.redisCache.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nodejs-demo.fullname" . }}-redis
  labels:
    app: redis
    {{- include "nodejs-demo.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: "{{ .Values.redisCache.image.repository }}:{{ .Values.redisCache.image.tag }}"
        ports:
        - containerPort: 6379
        resources:
          {{- toYaml .Values.redisCache.resources | nindent 12 }}
{{- end }}
