name: Build and Deploy Pipeline
on: 
    pull_request:
      branches: [ main ]
      types: [ opened, synchronize, reopened ]
    push:
      branches: [ main ]

jobs:
  build:
    uses: ./.github/workflows/reusable-build.yml
    with:
      node-version: '["18", "20"]'
      run-tests: true

  set-environment:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set-env.outputs.environment }}
    steps:
      - name: Determine environment
        id: set-env
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "environment=prod" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
            echo "environment=dev" >> $GITHUB_OUTPUT
          else
            echo "environment=stage" >> $GITHUB_OUTPUT
          fi
  deploy:
    needs: [build, set-environment]
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      environment: ${{ needs.set-environment.outputs.environment }}
      app-name: 'my-app'
    secrets:
      deploy-token: ${{ secrets.DEPLOY_TOKEN }}

  display-results:
    needs: [build,deploy]
    runs-on: ubuntu-latest
    steps:
      - name: Show results
        run: |
          echo "✅ Build completed at: ${{ needs.build.outputs.build-time }}"
          echo "🚀 Deployed to: ${{ needs.deploy.outputs.deployment-url }}"